name = "scienceonchain"
compatibility_date = "2024-01-01"

[build]
command = "npm run cloudflare-build"
cwd = "/"

[build.environment_variables]
NODE_VERSION = "22.16.0"
NPM_CONFIG_PRODUCTION = "false"

pages_build_output_dir = "dist"