[build]
command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
cwd = "/"
watch_dir = "src"

[build.environment_variables]
NODE_VERSION = "22.16.0"
NPM_CONFIG_PRODUCTION = "false"